[package]
edition = "2018"
name = "swc-wallaby"
version = "0.0.0"

[lib]
# [Crate not found in integration tests if crate-type = "cdylib"](https://github.com/rust-lang/cargo/issues/6659)
# [Ability to set crate-type depending on target](https://github.com/rust-lang/cargo/issues/4881)
crate-type = ["cdylib", "lib"]
name = "swc_wallaby"

[dependencies]
anyhow = "1.0"
backtrace = "0.3"
easy-error = "1.0.0"
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
path-clean = "0.1"
regex = "1.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc = "0.60"
swc_atoms = "0.2"
swc_common = { version = "0.13", features = ["concurrent", "sourcemap"] }
swc_css = "0.8.2"
swc_ecmascript = { version = "0.68", features = ["codegen", "minifier", "optimization", "parser", "react", "transforms", "typescript", "utils", "visit"] }
swc_ecma_preset_env = "0.47.0"
swc_ecma_ast = "0.54.0"
swc_node_base = "0.4.0"
swc_stylis = "0.5.0"
fxhash = "0.2.1"
retain_mut = "0.1.3"
pathdiff = "0.2.0"
rustc-hash = "1.1.0"
tracing = { version = "0.1.28", features = ["release_max_level_off"] }


[build-dependencies]
napi-build = "1"

[dev-dependencies]
swc_ecma_transforms_testing = "0.35.0"
testing = "0.14.0"

[profile.release]
lto = true
